import type {
  IncidentImpactRecord,
  IncidentRecord,
  ServerRecord,
  ServiceOwnerRecord,
  ServiceRecord,
  ServiceRelationRecord,
  TechStackRecord,
} from "./mockData";

// Generated by scripts/generate-mock-data.mjs from http://chainview.kro.kr:8080
// Do not edit manually.

export const generatedAt = "2026-06-17T02:26:06.478Z";

export const servers: ServerRecord[] = [
  {
    serverId: 20,
    serverName: "시험 Batch",
    hostName: "tst-batch01",
    ipAddress: "10.230.31.41",
    envCode: "TEST",
    osTypeCode: "LINUX",
    osVersion: "Rocky Linux 9.4",
    statusCode: "NORMAL",
    description: "통합 시험 배치 실행 서버",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 19,
    serverName: "개발 APP",
    hostName: "dev-app01",
    ipAddress: "10.220.12.31",
    envCode: "DEV",
    osTypeCode: "LINUX",
    osVersion: "Rocky Linux 9.4",
    statusCode: "NORMAL",
    description: "개발 공용 애플리케이션 서버",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 18,
    serverName: "스테이징 WAS",
    hostName: "stg-was01",
    ipAddress: "10.210.12.21",
    envCode: "STAGE",
    osTypeCode: "LINUX",
    osVersion: "Rocky Linux 9.4",
    statusCode: "MAINTENANCE",
    description: "운영 반영 전 통합 검증 WAS",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 17,
    serverName: "DR 채널 WEB",
    hostName: "dr-chn-web01",
    ipAddress: "10.110.11.11",
    envCode: "PROD",
    osTypeCode: "LINUX",
    osVersion: "Red Hat Enterprise Linux 8.10",
    statusCode: "NORMAL",
    description: "DR 센터 채널 WEB 대기 노드",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 16,
    serverName: "운영 DB 대표",
    hostName: "db-prd-oracle01",
    ipAddress: "10.60.11.111",
    envCode: "PROD",
    osTypeCode: "UNIX",
    osVersion: "AIX 7.2",
    statusCode: "NORMAL",
    description: "운영 Oracle 대표 메타 노드",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 15,
    serverName: "정보계 마트",
    hostName: "data-prd-mart01",
    ipAddress: "10.50.11.101",
    envCode: "PROD",
    osTypeCode: "LINUX",
    osVersion: "Red Hat Enterprise Linux 8.10",
    statusCode: "NORMAL",
    description: "정보계 마트/리포팅 운영 노드",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 14,
    serverName: "메시징/알림",
    hostName: "msg-prd-ums01",
    ipAddress: "10.40.41.91",
    envCode: "PROD",
    osTypeCode: "LINUX",
    osVersion: "Rocky Linux 9.4",
    statusCode: "NORMAL",
    description: "UMS/알림톡/SMS 연계 노드",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 13,
    serverName: "APM 모니터링",
    hostName: "mon-prd-apm01",
    ipAddress: "10.40.31.81",
    envCode: "PROD",
    osTypeCode: "LINUX",
    osVersion: "Rocky Linux 9.4",
    statusCode: "NORMAL",
    description: "Jennifer/APM/운영 대시보드 노드",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 12,
    serverName: "DevOps 플랫폼",
    hostName: "cmm-prd-devops01",
    ipAddress: "10.40.21.71",
    envCode: "PROD",
    osTypeCode: "LINUX",
    osVersion: "Rocky Linux 9.4",
    statusCode: "NORMAL",
    description: "GitLab/Jenkins/Nexus 운영 도구 노드",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 11,
    serverName: "인증 플랫폼 #2",
    hostName: "cmm-prd-auth02",
    ipAddress: "10.40.11.62",
    envCode: "PROD",
    osTypeCode: "LINUX",
    osVersion: "Red Hat Enterprise Linux 8.10",
    statusCode: "NORMAL",
    description: "인증 플랫폼 이중화 노드",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 10,
    serverName: "인증 플랫폼 #1",
    hostName: "cmm-prd-auth01",
    ipAddress: "10.40.11.61",
    envCode: "PROD",
    osTypeCode: "LINUX",
    osVersion: "Red Hat Enterprise Linux 8.10",
    statusCode: "NORMAL",
    description: "SSO/EAM/OAuth/간편인증 운영 노드",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 9,
    serverName: "대외계 MCI #2",
    hostName: "if-prd-mci02",
    ipAddress: "10.30.41.52",
    envCode: "PROD",
    osTypeCode: "LINUX",
    osVersion: "Rocky Linux 9.4",
    statusCode: "INCIDENT",
    description: "MCI/API 연계 운영 2호기 — 테스트 장애 시나리오 대상",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 8,
    serverName: "대외계 MCI #1",
    hostName: "if-prd-mci01",
    ipAddress: "10.30.41.51",
    envCode: "PROD",
    osTypeCode: "LINUX",
    osVersion: "Rocky Linux 9.4",
    statusCode: "NORMAL",
    description: "MCI/API 연계 운영 1호기",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 7,
    serverName: "기간계 배치 #1",
    hostName: "core-prd-batch01",
    ipAddress: "10.20.31.41",
    envCode: "PROD",
    osTypeCode: "UNIX",
    osVersion: "AIX 7.2",
    statusCode: "NORMAL",
    description: "기간계/TM/마감 배치 실행 노드",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 6,
    serverName: "기간계 WAS #2",
    hostName: "core-prd-was02",
    ipAddress: "10.20.21.32",
    envCode: "PROD",
    osTypeCode: "UNIX",
    osVersion: "AIX 7.2",
    statusCode: "NORMAL",
    description: "기간계 업무 서비스 운영 WAS 2호기",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 5,
    serverName: "기간계 WAS #1",
    hostName: "core-prd-was01",
    ipAddress: "10.20.21.31",
    envCode: "PROD",
    osTypeCode: "UNIX",
    osVersion: "AIX 7.2",
    statusCode: "NORMAL",
    description: "기간계 업무 서비스 운영 WAS 1호기",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 4,
    serverName: "채널 WAS #2",
    hostName: "chn-prd-was02",
    ipAddress: "10.10.12.22",
    envCode: "PROD",
    osTypeCode: "LINUX",
    osVersion: "Red Hat Enterprise Linux 8.10",
    statusCode: "NORMAL",
    description: "모바일 앱/챗봇 운영 WAS 이중화 노드",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 3,
    serverName: "채널 WAS #1",
    hostName: "chn-prd-was01",
    ipAddress: "10.10.12.21",
    envCode: "PROD",
    osTypeCode: "LINUX",
    osVersion: "Red Hat Enterprise Linux 8.10",
    statusCode: "NORMAL",
    description: "모바일 앱/채널 API 운영 WAS 노드",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 2,
    serverName: "채널 WEB #2",
    hostName: "chn-prd-web02",
    ipAddress: "10.10.11.12",
    envCode: "PROD",
    osTypeCode: "LINUX",
    osVersion: "Red Hat Enterprise Linux 8.10",
    statusCode: "NORMAL",
    description: "대고객 홈페이지/다이렉트 웹 프런트 이중화 노드",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serverId: 1,
    serverName: "채널 WEB #1",
    hostName: "chn-prd-web01",
    ipAddress: "10.10.11.11",
    envCode: "PROD",
    osTypeCode: "LINUX",
    osVersion: "Red Hat Enterprise Linux 8.10",
    statusCode: "NORMAL",
    description: "대고객 홈페이지/다이렉트 웹 프런트 운영 노드",
    createdAt: "2026-06-17 02:26",
    updatedAt: "2026-06-16 01:50"
  }
];

export const services: ServiceRecord[] = [
  {
    serviceId: 33,
    categoryPath: [
      "IFRS"
    ],
    serviceCode: "IFRS17_ENGINE",
    serviceName: "IFRS17 산출 엔진",
    serviceTypeCode: "BATCH",
    importanceCode: "HIGH",
    statusCode: "NORMAL",
    description: "IFRS17 결산 산출, 데이터 적재, 검증 리포트 생성을 수행",
    endpointUrl: "",
    serverId: 7,
    deployPath: "/batch/ifrs17",
    portInfo: "-",
    deploymentStatusCode: "RUNNING",
    instanceCount: 1,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 32,
    categoryPath: [
      "인사"
    ],
    serviceCode: "HR_PORTAL",
    serviceName: "인사 포털",
    serviceTypeCode: "WEB",
    importanceCode: "NORMAL",
    statusCode: "NORMAL",
    description: "사용자/조직 마스터, 인사 업무 연계를 제공",
    endpointUrl: "https://hr.chainview.local",
    serverId: 19,
    deployPath: "/app/hr-portal",
    portInfo: "8080",
    deploymentStatusCode: "RUNNING",
    instanceCount: 1,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 31,
    categoryPath: [
      "대출 신청/관리"
    ],
    serviceCode: "LOAN_CORE",
    serviceName: "대출 신청/관리 서비스",
    serviceTypeCode: "WEB",
    importanceCode: "HIGH",
    statusCode: "IMPACTED",
    description: "보험계약대출/신용대출 신청, 심사, 실행 상태를 관리",
    endpointUrl: "https://loan.chainview.local",
    serverId: 6,
    deployPath: "/app/loan",
    portInfo: "9097",
    deploymentStatusCode: "RUNNING",
    instanceCount: 2,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 30,
    categoryPath: [
      "수수료"
    ],
    serviceCode: "COMMISSION_CALC",
    serviceName: "수수료 산출 서비스",
    serviceTypeCode: "BATCH",
    importanceCode: "HIGH",
    statusCode: "NORMAL",
    description: "설계사 수수료 산출, 검증, 마감 배치를 수행",
    endpointUrl: "",
    serverId: 7,
    deployPath: "/batch/commission",
    portInfo: "-",
    deploymentStatusCode: "RUNNING",
    instanceCount: 1,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 29,
    categoryPath: [
      "수납/출납"
    ],
    serviceCode: "COLLECTION_PAYMENT",
    serviceName: "수납/출납 서비스",
    serviceTypeCode: "API",
    importanceCode: "CRITICAL",
    statusCode: "NORMAL",
    description: "보험료 수납, 지급, 출납 처리와 회계 인터페이스를 담당",
    endpointUrl: "https://pay.chainview.local/api",
    serverId: 5,
    deployPath: "/app/payment-api",
    portInfo: "9096",
    deploymentStatusCode: "RUNNING",
    instanceCount: 3,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 28,
    categoryPath: [
      "공통"
    ],
    serviceCode: "RETIREMENT_CORE",
    serviceName: "퇴직연금 공통 서비스",
    serviceTypeCode: "WEB",
    importanceCode: "HIGH",
    statusCode: "NORMAL",
    description: "퇴직연금 계약, 운용관리, 자산관리 공통 업무 처리",
    endpointUrl: "https://retire.chainview.local",
    serverId: 6,
    deployPath: "/app/retirement",
    portInfo: "9095",
    deploymentStatusCode: "RUNNING",
    instanceCount: 2,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 27,
    categoryPath: [
      "방카 포털"
    ],
    serviceCode: "BANK_PORTAL",
    serviceName: "방카 포털",
    serviceTypeCode: "WEB",
    importanceCode: "NORMAL",
    statusCode: "IMPACTED",
    description: "방카 제휴 채널 상품/청약/전문 연계 관리",
    endpointUrl: "https://bank.chainview.local",
    serverId: 5,
    deployPath: "/app/bank-portal",
    portInfo: "9094",
    deploymentStatusCode: "RUNNING",
    instanceCount: 2,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 26,
    categoryPath: [
      "VOC"
    ],
    serviceCode: "VOC_SYSTEM",
    serviceName: "VOC 통합 관리",
    serviceTypeCode: "WEB",
    importanceCode: "NORMAL",
    statusCode: "NORMAL",
    description: "민원/VOC 접수, 처리, 정독VOC, IT-VOC 관리",
    endpointUrl: "https://voc.chainview.local",
    serverId: 6,
    deployPath: "/app/voc",
    portInfo: "9093",
    deploymentStatusCode: "RUNNING",
    instanceCount: 1,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 25,
    categoryPath: [
      "고객상담센터"
    ],
    serviceCode: "CONTACT_CENTER",
    serviceName: "고객상담센터 시스템",
    serviceTypeCode: "WEB",
    importanceCode: "HIGH",
    statusCode: "NORMAL",
    description: "상담사 고객조회, 상담이력, 계약 주요 정보를 제공",
    endpointUrl: "https://cs.chainview.local",
    serverId: 6,
    deployPath: "/app/contact-center",
    portInfo: "9092",
    deploymentStatusCode: "RUNNING",
    instanceCount: 2,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 24,
    categoryPath: [
      "자동차TM"
    ],
    serviceCode: "AUTO_TM",
    serviceName: "자동차 TM 업무",
    serviceTypeCode: "WEB",
    importanceCode: "NORMAL",
    statusCode: "NORMAL",
    description: "자동차 TM 상담, 산출, 후속 연락 업무 지원",
    endpointUrl: "https://tm.chainview.local/auto",
    serverId: 5,
    deployPath: "/app/tm/auto",
    portInfo: "9091",
    deploymentStatusCode: "RUNNING",
    instanceCount: 2,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 23,
    categoryPath: [
      "BI/리포팅"
    ],
    serviceCode: "BI_REPORTING",
    serviceName: "BI 리포팅 서비스",
    serviceTypeCode: "WEB",
    importanceCode: "NORMAL",
    statusCode: "NORMAL",
    description: "임원/현업용 KPI, 통계, 자료추출 화면 제공",
    endpointUrl: "https://bi.chainview.local",
    serverId: 15,
    deployPath: "/opt/bi/reporting",
    portInfo: "8085",
    deploymentStatusCode: "RUNNING",
    instanceCount: 2,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 22,
    categoryPath: [
      "정보계 마트"
    ],
    serviceCode: "DATA_MART",
    serviceName: "정보계 데이터 마트",
    serviceTypeCode: "BATCH",
    importanceCode: "HIGH",
    statusCode: "NORMAL",
    description: "계약/채널/정산 데이터를 집계하여 정보계·리포팅에 제공",
    endpointUrl: "",
    serverId: 15,
    deployPath: "/data/mart/jobs",
    portInfo: "-",
    deploymentStatusCode: "RUNNING",
    instanceCount: 1,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 21,
    categoryPath: [
      "문서/이미지 솔루션"
    ],
    serviceCode: "DOC_IMAGE_HUB",
    serviceName: "문서/이미지 허브",
    serviceTypeCode: "API",
    importanceCode: "NORMAL",
    statusCode: "NORMAL",
    description: "전자문서, 이미지 OCR, PDF 변환, 첨부 이미지 조회 연계 서비스",
    endpointUrl: "https://doc.chainview.local/api",
    serverId: 14,
    deployPath: "/opt/app/doc-image",
    portInfo: "8091",
    deploymentStatusCode: "RUNNING",
    instanceCount: 2,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 20,
    categoryPath: [
      "메시징/알림 솔루션"
    ],
    serviceCode: "UMS_ALIMTALK",
    serviceName: "UMS 알림톡 발송",
    serviceTypeCode: "API",
    importanceCode: "HIGH",
    statusCode: "NORMAL",
    description: "알림톡, SMS, 이메일 발송 게이트웨이와 발송 이력 관리",
    endpointUrl: "https://ums.chainview.local/api",
    serverId: 14,
    deployPath: "/opt/app/ums",
    portInfo: "8090",
    deploymentStatusCode: "RUNNING",
    instanceCount: 2,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 19,
    categoryPath: [
      "ITSM"
    ],
    serviceCode: "ITSM_PORTAL",
    serviceName: "ITSM 운영 포털",
    serviceTypeCode: "WEB",
    importanceCode: "HIGH",
    statusCode: "NORMAL",
    description: "장애/변경/작업 요청 접수와 처리 이력 관리를 담당",
    endpointUrl: "https://itsm.chainview.local",
    serverId: 13,
    deployPath: "/opt/app/itsm",
    portInfo: "8088",
    deploymentStatusCode: "RUNNING",
    instanceCount: 1,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 18,
    categoryPath: [
      "APM 모니터링"
    ],
    serviceCode: "JENNIFER_APM",
    serviceName: "Jennifer APM 모니터링",
    serviceTypeCode: "WEB",
    importanceCode: "HIGH",
    statusCode: "NORMAL",
    description: "실시간 트랜잭션, JVM, WAS 상태 모니터링과 장애 알림 연계",
    endpointUrl: "https://apm.chainview.local",
    serverId: 13,
    deployPath: "/opt/jennifer/server",
    portInfo: "7900,7901",
    deploymentStatusCode: "RUNNING",
    instanceCount: 1,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 17,
    categoryPath: [
      "빌드/배포"
    ],
    serviceCode: "GITLAB_PLATFORM",
    serviceName: "GitLab/Jenkins 배포 플랫폼",
    serviceTypeCode: "WEB",
    importanceCode: "HIGH",
    statusCode: "NORMAL",
    description: "소스 형상관리, CI/CD, 배포 이력 조회를 제공",
    endpointUrl: "https://git.chainview.local",
    serverId: 12,
    deployPath: "/data/gitlab",
    portInfo: "80,443,2222",
    deploymentStatusCode: "RUNNING",
    instanceCount: 1,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 16,
    categoryPath: [
      "WEB/WAS"
    ],
    serviceCode: "JEUS_WEBWAS_POOL",
    serviceName: "JEUS WEB/WAS 공통 풀",
    serviceTypeCode: "API",
    importanceCode: "HIGH",
    statusCode: "NORMAL",
    description: "채널/기간계 서비스가 공통 사용하는 WEB/WAS 런타임 풀 관리 서비스",
    endpointUrl: "",
    serverId: 5,
    deployPath: "/jeus/domains/chain",
    portInfo: "9736",
    deploymentStatusCode: "RUNNING",
    instanceCount: 12,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 15,
    categoryPath: [
      "API Gateway"
    ],
    serviceCode: "API_GATEWAY",
    serviceName: "공통 API Gateway",
    serviceTypeCode: "API",
    importanceCode: "CRITICAL",
    statusCode: "NORMAL",
    description: "대고객/내부 API 라우팅, 인증 필터, 속도 제한을 담당",
    endpointUrl: "https://gateway.chainview.local",
    serverId: 10,
    deployPath: "/opt/gateway/api",
    portInfo: "9000,9443",
    deploymentStatusCode: "RUNNING",
    instanceCount: 6,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 14,
    categoryPath: [
      "MCI"
    ],
    serviceCode: "MCI_GATEWAY",
    serviceName: "채널통합 MCI 게이트웨이",
    serviceTypeCode: "API",
    importanceCode: "CRITICAL",
    statusCode: "IMPACTED",
    description: "채널계 요청을 기간계/대외계 표준 전문으로 변환·중계",
    endpointUrl: "https://mci.chainview.local/api",
    serverId: 8,
    deployPath: "/opt/mci/gateway",
    portInfo: "7100",
    deploymentStatusCode: "RUNNING",
    instanceCount: 8,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 13,
    categoryPath: [
      "간편인증"
    ],
    serviceCode: "SIMPLE_AUTH",
    serviceName: "간편인증 연계",
    serviceTypeCode: "API",
    importanceCode: "HIGH",
    statusCode: "NORMAL",
    description: "카카오/네이버/PASS 등 간편인증 중계 및 결과 검증 서비스",
    endpointUrl: "https://auth.chainview.local/simple",
    serverId: 11,
    deployPath: "/opt/auth/simple",
    portInfo: "8083",
    deploymentStatusCode: "RUNNING",
    instanceCount: 2,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 12,
    categoryPath: [
      "OAuth 인증 서비스"
    ],
    serviceCode: "OAUTH_AUTH",
    serviceName: "OAuth 인증 API",
    serviceTypeCode: "API",
    importanceCode: "HIGH",
    statusCode: "NORMAL",
    description: "모바일/외부 연계용 OAuth2 토큰 발급 및 검증 API",
    endpointUrl: "https://auth.chainview.local/oauth",
    serverId: 10,
    deployPath: "/opt/auth/oauth",
    portInfo: "8082",
    deploymentStatusCode: "RUNNING",
    instanceCount: 4,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 11,
    categoryPath: [
      "SSO/EAM"
    ],
    serviceCode: "SSO_EAM",
    serviceName: "SSO/EAM 통합 인증",
    serviceTypeCode: "API",
    importanceCode: "CRITICAL",
    statusCode: "INCIDENT",
    description: "내부/대고객 서비스 로그인, 세션, 권한 검증을 제공하는 인증 기반 서비스",
    endpointUrl: "https://auth.chainview.local/sso",
    serverId: 10,
    deployPath: "/opt/auth/sso",
    portInfo: "8081,8444",
    deploymentStatusCode: "RUNNING",
    instanceCount: 4,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 10,
    categoryPath: [
      "파일전송"
    ],
    serviceCode: "FILE_TRANSFER_HUB",
    serviceName: "파일전송 허브",
    serviceTypeCode: "BATCH",
    importanceCode: "HIGH",
    statusCode: "NORMAL",
    description: "SFTP/FTMS 기반 일배치 파일 송수신과 재처리 관리를 담당",
    endpointUrl: "",
    serverId: 7,
    deployPath: "/batch/file-transfer",
    portInfo: "-",
    deploymentStatusCode: "RUNNING",
    instanceCount: 1,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 9,
    categoryPath: [
      "공공기관 연계"
    ],
    serviceCode: "GOV_PUBLIC_IF",
    serviceName: "공공기관 연계 서비스",
    serviceTypeCode: "EXTERNAL",
    importanceCode: "HIGH",
    statusCode: "NORMAL",
    description: "건보, 행안부, 신용정보 등 외부 기관 연계 상태를 관리",
    endpointUrl: "https://if.chainview.local/gov",
    serverId: 9,
    deployPath: "/opt/app/gov-if",
    portInfo: "18110",
    deploymentStatusCode: "RUNNING",
    instanceCount: 2,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 8,
    categoryPath: [
      "마이데이터"
    ],
    serviceCode: "MYDATA_PROVIDER",
    serviceName: "마이데이터 제공 서비스",
    serviceTypeCode: "API",
    importanceCode: "CRITICAL",
    statusCode: "NORMAL",
    description: "마이데이터 2.0 대응 제공 API와 전송 이력을 관리",
    endpointUrl: "https://mydata.chainview.local/provider",
    serverId: 8,
    deployPath: "/opt/app/mydata-provider",
    portInfo: "18100",
    deploymentStatusCode: "RUNNING",
    instanceCount: 4,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 7,
    categoryPath: [
      "Megaware 대내외계"
    ],
    serviceCode: "MEGAWARE_HUB",
    serviceName: "Megaware 대외계 허브",
    serviceTypeCode: "API",
    importanceCode: "CRITICAL",
    statusCode: "IMPACTED",
    description: "공공기관, 금융기관, 제휴사 전문 송수신을 중계하는 대외계 허브",
    endpointUrl: "https://if.chainview.local/megaware",
    serverId: 8,
    deployPath: "/opt/megaware/hub",
    portInfo: "7001,7002",
    deploymentStatusCode: "RUNNING",
    instanceCount: 6,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 6,
    categoryPath: [
      "모바일 전자청약"
    ],
    serviceCode: "MOBILE_E_CONTRACT",
    serviceName: "모바일 전자청약",
    serviceTypeCode: "WEB",
    importanceCode: "CRITICAL",
    statusCode: "IMPACTED",
    description: "모바일 기반 전자청약, 전자서명, 증빙 이미지 업로드를 처리",
    endpointUrl: "https://econ.chainview.local",
    serverId: 3,
    deployPath: "/opt/app/mobile-e-contract",
    portInfo: "18083",
    deploymentStatusCode: "RUNNING",
    instanceCount: 6,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 5,
    categoryPath: [
      "영업지원 포털"
    ],
    serviceCode: "SALES_PORTAL",
    serviceName: "영업지원 포털",
    serviceTypeCode: "WEB",
    importanceCode: "HIGH",
    statusCode: "IMPACTED",
    description: "설계사/영업관리자가 고객·계약·활동 정보를 조회하는 내부 포털",
    endpointUrl: "https://sales.chainview.local",
    serverId: 5,
    deployPath: "/app/sales-portal",
    portInfo: "9080",
    deploymentStatusCode: "RUNNING",
    instanceCount: 4,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 4,
    categoryPath: [
      "챗봇"
    ],
    serviceCode: "CHATBOT_ASSIST",
    serviceName: "AI 상담 챗봇",
    serviceTypeCode: "API",
    importanceCode: "NORMAL",
    statusCode: "NORMAL",
    description: "계약조회, 보험금청구 안내, 상담사 연결 전 사전 응대 기능",
    endpointUrl: "https://chatbot.chainview.local/api",
    serverId: 4,
    deployPath: "/opt/app/chatbot",
    portInfo: "18082",
    deploymentStatusCode: "RUNNING",
    instanceCount: 2,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 3,
    categoryPath: [
      "다이렉트 홈페이지"
    ],
    serviceCode: "DIRECT_SALES_WEB",
    serviceName: "다이렉트 가입 홈페이지",
    serviceTypeCode: "WEB",
    importanceCode: "CRITICAL",
    statusCode: "IMPACTED",
    description: "자동차/장기보험 다이렉트 산출·가입·결제 흐름을 제공",
    endpointUrl: "https://direct.chainview.local",
    serverId: 2,
    deployPath: "/app/web/direct",
    portInfo: "80,443",
    deploymentStatusCode: "RUNNING",
    instanceCount: 4,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 2,
    categoryPath: [
      "홈페이지"
    ],
    serviceCode: "HOMEPAGE_WEB",
    serviceName: "대표 홈페이지",
    serviceTypeCode: "WEB",
    importanceCode: "HIGH",
    statusCode: "IMPACTED",
    description: "상품 안내, 고객센터, 공시, 계약조회 진입을 제공하는 대고객 웹 서비스",
    endpointUrl: "https://www.chainview.local",
    serverId: 1,
    deployPath: "/app/web/homepage",
    portInfo: "80,443",
    deploymentStatusCode: "RUNNING",
    instanceCount: 4,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    serviceId: 1,
    categoryPath: [
      "대고객 앱/웹"
    ],
    serviceCode: "MOBILE_APP",
    serviceName: "대표 모바일 앱",
    serviceTypeCode: "WEB",
    importanceCode: "CRITICAL",
    statusCode: "IMPACTED",
    description: "고객 계약조회, 보험금 청구, 간편인증, 알림 연계를 제공하는 대표 모바일 채널",
    endpointUrl: "https://m.chainview.local/app",
    serverId: 3,
    deployPath: "/opt/app/mobile-app",
    portInfo: "8080,8443",
    deploymentStatusCode: "RUNNING",
    instanceCount: 10,
    createdBy: "api",
    updatedBy: "api",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  }
];

export const serviceRelations: ServiceRelationRecord[] = [
  {
    relationId: 47,
    sourceServiceId: 14,
    targetServiceId: 14,
    relationTypeCode: "ETC",
    mandatoryYn: "N",
    relationStatusCode: "ACTIVE",
    description: "자기 상태 점검/루프백 테스트",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 46,
    sourceServiceId: 15,
    targetServiceId: 11,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "Gateway 인증 필터",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 45,
    sourceServiceId: 17,
    targetServiceId: 20,
    relationTypeCode: "REST",
    mandatoryYn: "N",
    relationStatusCode: "ACTIVE",
    description: "배포 결과 알림",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 44,
    sourceServiceId: 19,
    targetServiceId: 20,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "처리 알림",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 43,
    sourceServiceId: 18,
    targetServiceId: 20,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "장애 알림 발송",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 42,
    sourceServiceId: 23,
    targetServiceId: 22,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "BI 조회",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 41,
    sourceServiceId: 33,
    targetServiceId: 23,
    relationTypeCode: "REST",
    mandatoryYn: "N",
    relationStatusCode: "ACTIVE",
    description: "결산 리포트 조회",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 40,
    sourceServiceId: 33,
    targetServiceId: 22,
    relationTypeCode: "FILE",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "결산 데이터 수집",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 39,
    sourceServiceId: 31,
    targetServiceId: 20,
    relationTypeCode: "REST",
    mandatoryYn: "N",
    relationStatusCode: "ACTIVE",
    description: "대출 진행 알림",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 38,
    sourceServiceId: 31,
    targetServiceId: 10,
    relationTypeCode: "FILE",
    mandatoryYn: "N",
    relationStatusCode: "ACTIVE",
    description: "대출 마감 파일",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 37,
    sourceServiceId: 31,
    targetServiceId: 7,
    relationTypeCode: "SOAP",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "신용정보/외부기관 연계",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 36,
    sourceServiceId: 31,
    targetServiceId: 11,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "대출 사용자 인증",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 35,
    sourceServiceId: 29,
    targetServiceId: 10,
    relationTypeCode: "FILE",
    mandatoryYn: "N",
    relationStatusCode: "ACTIVE",
    description: "은행 파일 송수신",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 34,
    sourceServiceId: 29,
    targetServiceId: 7,
    relationTypeCode: "SOAP",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "금융기관 납입 결과",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 33,
    sourceServiceId: 29,
    targetServiceId: 14,
    relationTypeCode: "MQ",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "회계/기간계 전문",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 32,
    sourceServiceId: 28,
    targetServiceId: 23,
    relationTypeCode: "REST",
    mandatoryYn: "N",
    relationStatusCode: "ACTIVE",
    description: "리포트 조회",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 31,
    sourceServiceId: 28,
    targetServiceId: 22,
    relationTypeCode: "FILE",
    mandatoryYn: "N",
    relationStatusCode: "ACTIVE",
    description: "운용/통계 마트 적재",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 30,
    sourceServiceId: 28,
    targetServiceId: 14,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "기간계 계약 연계",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 29,
    sourceServiceId: 27,
    targetServiceId: 7,
    relationTypeCode: "SOAP",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "제휴 은행 전문",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 28,
    sourceServiceId: 27,
    targetServiceId: 11,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "방카 사용자 인증",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 27,
    sourceServiceId: 9,
    targetServiceId: 10,
    relationTypeCode: "FILE",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "기관 파일 송수신",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 26,
    sourceServiceId: 9,
    targetServiceId: 7,
    relationTypeCode: "SOAP",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "공공기관 전문 연계",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 25,
    sourceServiceId: 8,
    targetServiceId: 22,
    relationTypeCode: "FILE",
    mandatoryYn: "N",
    relationStatusCode: "ACTIVE",
    description: "전송 이력 마트 적재",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 24,
    sourceServiceId: 8,
    targetServiceId: 7,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "대외계 송수신",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 23,
    sourceServiceId: 8,
    targetServiceId: 12,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "OAuth 토큰 검증",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 22,
    sourceServiceId: 6,
    targetServiceId: 7,
    relationTypeCode: "SOAP",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "외부 검증 전문",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 21,
    sourceServiceId: 6,
    targetServiceId: 21,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "청약 문서/PDF 처리",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 20,
    sourceServiceId: 6,
    targetServiceId: 13,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "간편인증",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 19,
    sourceServiceId: 6,
    targetServiceId: 11,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "청약자 인증",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 18,
    sourceServiceId: 5,
    targetServiceId: 30,
    relationTypeCode: "FILE",
    mandatoryYn: "N",
    relationStatusCode: "ACTIVE",
    description: "수수료 결과 조회",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 17,
    sourceServiceId: 5,
    targetServiceId: 14,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "기간계 계약/고객 조회",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 16,
    sourceServiceId: 5,
    targetServiceId: 11,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "내부 사용자 인증",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 15,
    sourceServiceId: 4,
    targetServiceId: 26,
    relationTypeCode: "REST",
    mandatoryYn: "N",
    relationStatusCode: "ACTIVE",
    description: "민원 접수 연계",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 14,
    sourceServiceId: 4,
    targetServiceId: 25,
    relationTypeCode: "REST",
    mandatoryYn: "N",
    relationStatusCode: "ACTIVE",
    description: "상담사 연결",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 13,
    sourceServiceId: 4,
    targetServiceId: 15,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "챗봇 조회 API",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 12,
    sourceServiceId: 3,
    targetServiceId: 29,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "보험료 결제",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 11,
    sourceServiceId: 3,
    targetServiceId: 7,
    relationTypeCode: "SOAP",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "외부 보험요율/검증 전문",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 10,
    sourceServiceId: 3,
    targetServiceId: 11,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "가입자 인증",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 9,
    sourceServiceId: 3,
    targetServiceId: 15,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "다이렉트 산출/가입 API",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 8,
    sourceServiceId: 2,
    targetServiceId: 20,
    relationTypeCode: "REST",
    mandatoryYn: "N",
    relationStatusCode: "ACTIVE",
    description: "상담/민원 알림",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 7,
    sourceServiceId: 2,
    targetServiceId: 11,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "홈페이지 로그인",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 6,
    sourceServiceId: 2,
    targetServiceId: 15,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "홈페이지 API 라우팅",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 5,
    sourceServiceId: 1,
    targetServiceId: 21,
    relationTypeCode: "REST",
    mandatoryYn: "N",
    relationStatusCode: "ACTIVE",
    description: "보험금 청구 이미지 업로드",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 4,
    sourceServiceId: 1,
    targetServiceId: 20,
    relationTypeCode: "REST",
    mandatoryYn: "N",
    relationStatusCode: "ACTIVE",
    description: "푸시/알림톡 발송",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 3,
    sourceServiceId: 1,
    targetServiceId: 13,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "간편인증 본인확인",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 2,
    sourceServiceId: 1,
    targetServiceId: 11,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "모바일 로그인/권한 확인",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  },
  {
    relationId: 1,
    sourceServiceId: 1,
    targetServiceId: 15,
    relationTypeCode: "REST",
    mandatoryYn: "Y",
    relationStatusCode: "ACTIVE",
    description: "모바일 앱 공통 API 라우팅",
    createdAt: "2026-06-16 01:50",
    updatedAt: "2026-06-16 01:50"
  }
];

export const techStacks: TechStackRecord[] = [
  {
    techStackId: 16,
    serviceId: 4,
    techTypeName: "언어",
    techName: "Python",
    versionText: "-",
    vendorName: "Python Software Foundation"
  },
  {
    techStackId: 17,
    serviceId: 4,
    techTypeName: "백엔드 프레임워크",
    techName: "FastAPI",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 18,
    serviceId: 4,
    techTypeName: "기타 솔루션",
    techName: "AI Agent",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 78,
    serviceId: 23,
    techTypeName: "데이터베이스",
    techName: "Oracle Database",
    versionText: "19c",
    vendorName: "Oracle"
  },
  {
    techStackId: 76,
    serviceId: 23,
    techTypeName: "리포팅 솔루션",
    techName: "BI Report",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 77,
    serviceId: 23,
    techTypeName: "리포팅 솔루션",
    techName: "OZ Report",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 62,
    serviceId: 17,
    techTypeName: "데이터베이스",
    techName: "PostgreSQL",
    versionText: "-",
    vendorName: "PostgreSQL Global Development Group"
  },
  {
    techStackId: 59,
    serviceId: 17,
    techTypeName: "DevOps 도구",
    techName: "GitLab",
    versionText: "-",
    vendorName: "GitLab"
  },
  {
    techStackId: 60,
    serviceId: 17,
    techTypeName: "DevOps 도구",
    techName: "Jenkins",
    versionText: "-",
    vendorName: "Jenkins"
  },
  {
    techStackId: 61,
    serviceId: 17,
    techTypeName: "DevOps 도구",
    techName: "Nexus",
    versionText: "-",
    vendorName: "Sonatype"
  },
  {
    techStackId: 105,
    serviceId: 33,
    techTypeName: "언어",
    techName: "Java",
    versionText: "11",
    vendorName: "Oracle"
  },
  {
    techStackId: 107,
    serviceId: 33,
    techTypeName: "데이터베이스",
    techName: "Oracle Database",
    versionText: "19c",
    vendorName: "Oracle"
  },
  {
    techStackId: 106,
    serviceId: 33,
    techTypeName: "배치 프레임워크",
    techName: "TeraStream",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 66,
    serviceId: 19,
    techTypeName: "언어",
    techName: "Java",
    versionText: "11",
    vendorName: "Oracle"
  },
  {
    techStackId: 65,
    serviceId: 19,
    techTypeName: "기타 솔루션",
    techName: "ITSM",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 64,
    serviceId: 18,
    techTypeName: "모니터링 도구",
    techName: "Grafana",
    versionText: "-",
    vendorName: "Grafana Labs"
  },
  {
    techStackId: 63,
    serviceId: 18,
    techTypeName: "모니터링 도구",
    techName: "Jennifer",
    versionText: "-",
    vendorName: "JenniferSoft"
  },
  {
    techStackId: 58,
    serviceId: 16,
    techTypeName: "런타임",
    techName: "IBM Semeru Runtime",
    versionText: "11",
    vendorName: "IBM"
  },
  {
    techStackId: 56,
    serviceId: 16,
    techTypeName: "미들웨어",
    techName: "JEUS",
    versionText: "-",
    vendorName: "TmaxSoft"
  },
  {
    techStackId: 57,
    serviceId: 16,
    techTypeName: "미들웨어",
    techName: "WebtoB",
    versionText: "-",
    vendorName: "TmaxSoft"
  },
  {
    techStackId: 28,
    serviceId: 7,
    techTypeName: "언어",
    techName: "Java",
    versionText: "8",
    vendorName: "Oracle"
  },
  {
    techStackId: 30,
    serviceId: 7,
    techTypeName: "데이터베이스",
    techName: "Oracle Database",
    versionText: "19c",
    vendorName: "Oracle"
  },
  {
    techStackId: 29,
    serviceId: 7,
    techTypeName: "미들웨어",
    techName: "JEUS",
    versionText: "-",
    vendorName: "TmaxSoft"
  },
  {
    techStackId: 27,
    serviceId: 7,
    techTypeName: "연계 솔루션",
    techName: "Megaware",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 46,
    serviceId: 12,
    techTypeName: "언어",
    techName: "Java",
    versionText: "17",
    vendorName: "Oracle"
  },
  {
    techStackId: 47,
    serviceId: 12,
    techTypeName: "백엔드 프레임워크",
    techName: "Spring Security",
    versionText: "6.x",
    vendorName: "Broadcom"
  },
  {
    techStackId: 45,
    serviceId: 12,
    techTypeName: "보안 솔루션",
    techName: "OAuth",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 42,
    serviceId: 11,
    techTypeName: "언어",
    techName: "Java",
    versionText: "11",
    vendorName: "Oracle"
  },
  {
    techStackId: 44,
    serviceId: 11,
    techTypeName: "데이터베이스",
    techName: "Oracle Database",
    versionText: "19c",
    vendorName: "Oracle"
  },
  {
    techStackId: 43,
    serviceId: 11,
    techTypeName: "미들웨어",
    techName: "WebLogic",
    versionText: "-",
    vendorName: "Oracle"
  },
  {
    techStackId: 41,
    serviceId: 11,
    techTypeName: "보안 솔루션",
    techName: "SSO/EAM",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 69,
    serviceId: 20,
    techTypeName: "언어",
    techName: "Java",
    versionText: "11",
    vendorName: "Oracle"
  },
  {
    techStackId: 68,
    serviceId: 20,
    techTypeName: "기타 솔루션",
    techName: "AlimTalk",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 67,
    serviceId: 20,
    techTypeName: "기타 솔루션",
    techName: "UMS",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 85,
    serviceId: 26,
    techTypeName: "언어",
    techName: "Java",
    versionText: "11",
    vendorName: "Oracle"
  },
  {
    techStackId: 86,
    serviceId: 26,
    techTypeName: "백엔드 프레임워크",
    techName: "Spring Boot",
    versionText: "2.x",
    vendorName: "VMware"
  },
  {
    techStackId: 49,
    serviceId: 13,
    techTypeName: "언어",
    techName: "Java",
    versionText: "11",
    vendorName: "Oracle"
  },
  {
    techStackId: 48,
    serviceId: 13,
    techTypeName: "보안 솔루션",
    techName: "INISAFE",
    versionText: "-",
    vendorName: "INITECH"
  },
  {
    techStackId: 82,
    serviceId: 25,
    techTypeName: "언어",
    techName: "Java",
    versionText: "8",
    vendorName: "Oracle"
  },
  {
    techStackId: 83,
    serviceId: 25,
    techTypeName: "백엔드 프레임워크",
    techName: "Spring MVC",
    versionText: "4.x",
    vendorName: "VMware"
  },
  {
    techStackId: 84,
    serviceId: 25,
    techTypeName: "데이터베이스",
    techName: "Oracle Database",
    versionText: "11g",
    vendorName: "Oracle"
  },
  {
    techStackId: 37,
    serviceId: 9,
    techTypeName: "언어",
    techName: "Java",
    versionText: "8",
    vendorName: "Oracle"
  },
  {
    techStackId: 36,
    serviceId: 9,
    techTypeName: "연계 솔루션",
    techName: "SFTP",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 35,
    serviceId: 9,
    techTypeName: "연계 솔루션",
    techName: "SOAP",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 53,
    serviceId: 15,
    techTypeName: "언어",
    techName: "Java",
    versionText: "17",
    vendorName: "Oracle"
  },
  {
    techStackId: 54,
    serviceId: 15,
    techTypeName: "백엔드 프레임워크",
    techName: "Spring Cloud",
    versionText: "2023.x",
    vendorName: "Broadcom"
  },
  {
    techStackId: 55,
    serviceId: 15,
    techTypeName: "DevOps 도구",
    techName: "Docker",
    versionText: "-",
    vendorName: "Docker"
  },
  {
    techStackId: 12,
    serviceId: 3,
    techTypeName: "언어",
    techName: "Java",
    versionText: "17",
    vendorName: "Oracle"
  },
  {
    techStackId: 13,
    serviceId: 3,
    techTypeName: "백엔드 프레임워크",
    techName: "Spring Boot",
    versionText: "3.x",
    vendorName: "VMware"
  },
  {
    techStackId: 14,
    serviceId: 3,
    techTypeName: "프론트엔드 프레임워크",
    techName: "React",
    versionText: "-",
    vendorName: "Meta"
  },
  {
    techStackId: 15,
    serviceId: 3,
    techTypeName: "데이터베이스",
    techName: "Oracle Database",
    versionText: "19c",
    vendorName: "Oracle"
  },
  {
    techStackId: 99,
    serviceId: 31,
    techTypeName: "언어",
    techName: "Java",
    versionText: "11",
    vendorName: "Oracle"
  },
  {
    techStackId: 100,
    serviceId: 31,
    techTypeName: "백엔드 프레임워크",
    techName: "Spring MVC",
    versionText: "5.x",
    vendorName: "VMware"
  },
  {
    techStackId: 101,
    serviceId: 31,
    techTypeName: "데이터베이스",
    techName: "Oracle Database",
    versionText: "19c",
    vendorName: "Oracle"
  },
  {
    techStackId: 1,
    serviceId: 1,
    techTypeName: "언어",
    techName: "Java",
    versionText: "17",
    vendorName: "Oracle"
  },
  {
    techStackId: 2,
    serviceId: 1,
    techTypeName: "런타임",
    techName: "JDK",
    versionText: "17",
    vendorName: "Oracle"
  },
  {
    techStackId: 3,
    serviceId: 1,
    techTypeName: "백엔드 프레임워크",
    techName: "Spring Boot",
    versionText: "3.x",
    vendorName: "VMware"
  },
  {
    techStackId: 4,
    serviceId: 1,
    techTypeName: "모바일 프레임워크",
    techName: "Flutter",
    versionText: "-",
    vendorName: "Google"
  },
  {
    techStackId: 5,
    serviceId: 1,
    techTypeName: "데이터베이스",
    techName: "Oracle Database",
    versionText: "19c",
    vendorName: "Oracle"
  },
  {
    techStackId: 6,
    serviceId: 1,
    techTypeName: "연계 솔루션",
    techName: "REST API",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 7,
    serviceId: 2,
    techTypeName: "언어",
    techName: "Java",
    versionText: "11",
    vendorName: "Oracle"
  },
  {
    techStackId: 8,
    serviceId: 2,
    techTypeName: "백엔드 프레임워크",
    techName: "Spring MVC",
    versionText: "-",
    vendorName: "VMware"
  },
  {
    techStackId: 9,
    serviceId: 2,
    techTypeName: "프론트엔드 프레임워크",
    techName: "jQuery",
    versionText: "-",
    vendorName: "OpenJS Foundation"
  },
  {
    techStackId: 11,
    serviceId: 2,
    techTypeName: "미들웨어",
    techName: "JEUS",
    versionText: "-",
    vendorName: "TmaxSoft"
  },
  {
    techStackId: 10,
    serviceId: 2,
    techTypeName: "미들웨어",
    techName: "WebtoB",
    versionText: "-",
    vendorName: "TmaxSoft"
  },
  {
    techStackId: 31,
    serviceId: 8,
    techTypeName: "언어",
    techName: "Java",
    versionText: "17",
    vendorName: "Oracle"
  },
  {
    techStackId: 32,
    serviceId: 8,
    techTypeName: "백엔드 프레임워크",
    techName: "Spring Boot",
    versionText: "3.x",
    vendorName: "VMware"
  },
  {
    techStackId: 33,
    serviceId: 8,
    techTypeName: "연계 솔루션",
    techName: "OpenAPI",
    versionText: "3.x",
    vendorName: "OpenAPI Initiative"
  },
  {
    techStackId: 34,
    serviceId: 8,
    techTypeName: "보안 솔루션",
    techName: "OAuth",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 23,
    serviceId: 6,
    techTypeName: "언어",
    techName: "Java",
    versionText: "11",
    vendorName: "Oracle"
  },
  {
    techStackId: 24,
    serviceId: 6,
    techTypeName: "백엔드 프레임워크",
    techName: "Spring Framework",
    versionText: "5.x",
    vendorName: "VMware"
  },
  {
    techStackId: 25,
    serviceId: 6,
    techTypeName: "보안 솔루션",
    techName: "PKI",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 26,
    serviceId: 6,
    techTypeName: "문서/이미지 솔루션",
    techName: "PDF Converter",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 70,
    serviceId: 21,
    techTypeName: "문서/이미지 솔루션",
    techName: "EDMS",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 71,
    serviceId: 21,
    techTypeName: "문서/이미지 솔루션",
    techName: "OCR",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 72,
    serviceId: 21,
    techTypeName: "문서/이미지 솔루션",
    techName: "PDF Converter",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 87,
    serviceId: 27,
    techTypeName: "언어",
    techName: "Java",
    versionText: "8",
    vendorName: "Oracle"
  },
  {
    techStackId: 88,
    serviceId: 27,
    techTypeName: "백엔드 프레임워크",
    techName: "전자정부프레임워크",
    versionText: "3.x",
    vendorName: "NIA"
  },
  {
    techStackId: 89,
    serviceId: 27,
    techTypeName: "연계 솔루션",
    techName: "SOAP",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 93,
    serviceId: 29,
    techTypeName: "언어",
    techName: "Java",
    versionText: "8",
    vendorName: "Oracle"
  },
  {
    techStackId: 94,
    serviceId: 29,
    techTypeName: "백엔드 프레임워크",
    techName: "Anyframe",
    versionText: "5.x",
    vendorName: "Samsung SDS"
  },
  {
    techStackId: 95,
    serviceId: 29,
    techTypeName: "연계 솔루션",
    techName: "IBM MQ",
    versionText: "-",
    vendorName: "IBM"
  },
  {
    techStackId: 96,
    serviceId: 30,
    techTypeName: "언어",
    techName: "PL/SQL",
    versionText: "-",
    vendorName: "Oracle"
  },
  {
    techStackId: 98,
    serviceId: 30,
    techTypeName: "데이터베이스",
    techName: "Oracle Database",
    versionText: "19c",
    vendorName: "Oracle"
  },
  {
    techStackId: 97,
    serviceId: 30,
    techTypeName: "배치 프레임워크",
    techName: "Control-M",
    versionText: "-",
    vendorName: "BMC"
  },
  {
    techStackId: 19,
    serviceId: 5,
    techTypeName: "언어",
    techName: "Java",
    versionText: "8",
    vendorName: "Oracle"
  },
  {
    techStackId: 20,
    serviceId: 5,
    techTypeName: "백엔드 프레임워크",
    techName: "전자정부프레임워크",
    versionText: "3.x",
    vendorName: "NIA"
  },
  {
    techStackId: 21,
    serviceId: 5,
    techTypeName: "프론트엔드 프레임워크",
    techName: "Nexacro",
    versionText: "-",
    vendorName: "TOBESOFT"
  },
  {
    techStackId: 22,
    serviceId: 5,
    techTypeName: "데이터베이스",
    techName: "Oracle Database",
    versionText: "11g",
    vendorName: "Oracle"
  },
  {
    techStackId: 102,
    serviceId: 32,
    techTypeName: "언어",
    techName: "Java",
    versionText: "17",
    vendorName: "Oracle"
  },
  {
    techStackId: 103,
    serviceId: 32,
    techTypeName: "백엔드 프레임워크",
    techName: "Spring Boot",
    versionText: "3.x",
    vendorName: "VMware"
  },
  {
    techStackId: 104,
    serviceId: 32,
    techTypeName: "프론트엔드 프레임워크",
    techName: "Vue.js",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 79,
    serviceId: 24,
    techTypeName: "언어",
    techName: "Java",
    versionText: "8",
    vendorName: "Oracle"
  },
  {
    techStackId: 80,
    serviceId: 24,
    techTypeName: "백엔드 프레임워크",
    techName: "Anyframe",
    versionText: "3.x",
    vendorName: "Samsung SDS"
  },
  {
    techStackId: 81,
    serviceId: 24,
    techTypeName: "프론트엔드 프레임워크",
    techName: "MiPlatform",
    versionText: "-",
    vendorName: "TOBESOFT"
  },
  {
    techStackId: 75,
    serviceId: 22,
    techTypeName: "언어",
    techName: "PL/SQL",
    versionText: "-",
    vendorName: "Oracle"
  },
  {
    techStackId: 73,
    serviceId: 22,
    techTypeName: "데이터베이스",
    techName: "Oracle Database",
    versionText: "19c",
    vendorName: "Oracle"
  },
  {
    techStackId: 74,
    serviceId: 22,
    techTypeName: "배치 프레임워크",
    techName: "TeraStream",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 51,
    serviceId: 14,
    techTypeName: "언어",
    techName: "Java",
    versionText: "8",
    vendorName: "Oracle"
  },
  {
    techStackId: 52,
    serviceId: 14,
    techTypeName: "미들웨어",
    techName: "Tmax",
    versionText: "-",
    vendorName: "TmaxSoft"
  },
  {
    techStackId: 50,
    serviceId: 14,
    techTypeName: "연계 솔루션",
    techName: "iGate MCI",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 90,
    serviceId: 28,
    techTypeName: "언어",
    techName: "Java",
    versionText: "11",
    vendorName: "Oracle"
  },
  {
    techStackId: 91,
    serviceId: 28,
    techTypeName: "백엔드 프레임워크",
    techName: "Spring Framework",
    versionText: "5.x",
    vendorName: "VMware"
  },
  {
    techStackId: 92,
    serviceId: 28,
    techTypeName: "데이터베이스",
    techName: "Oracle Database",
    versionText: "19c",
    vendorName: "Oracle"
  },
  {
    techStackId: 40,
    serviceId: 10,
    techTypeName: "언어",
    techName: "Shell Script",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 38,
    serviceId: 10,
    techTypeName: "연계 솔루션",
    techName: "SFTP",
    versionText: "-",
    vendorName: "-"
  },
  {
    techStackId: 39,
    serviceId: 10,
    techTypeName: "배치 프레임워크",
    techName: "Shell Batch",
    versionText: "-",
    vendorName: "-"
  }
];

export const serviceOwners: ServiceOwnerRecord[] = [
  {
    serviceOwnerId: 6,
    serviceId: 4,
    ownerTypeCode: "GROUP",
    ownerName: "챗봇 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 30,
    serviceId: 23,
    ownerTypeCode: "GROUP",
    ownerName: "정보계 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 23,
    serviceId: 17,
    ownerTypeCode: "GROUP",
    ownerName: "DevOps 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 40,
    serviceId: 33,
    ownerTypeCode: "GROUP",
    ownerName: "자산운용/IFRS 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 25,
    serviceId: 19,
    ownerTypeCode: "GROUP",
    ownerName: "모니터링 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 24,
    serviceId: 18,
    ownerTypeCode: "GROUP",
    ownerName: "모니터링 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 22,
    serviceId: 16,
    ownerTypeCode: "GROUP",
    ownerName: "미들웨어 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 10,
    serviceId: 7,
    ownerTypeCode: "GROUP",
    ownerName: "대내외계 온콜그룹",
    responsibilityCode: "ALERT"
  },
  {
    serviceOwnerId: 9,
    serviceId: 7,
    ownerTypeCode: "GROUP",
    ownerName: "대내외계 솔루션 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 17,
    serviceId: 12,
    ownerTypeCode: "GROUP",
    ownerName: "인증/권한 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 16,
    serviceId: 11,
    ownerTypeCode: "GROUP",
    ownerName: "공통플랫폼 온콜그룹",
    responsibilityCode: "ALERT"
  },
  {
    serviceOwnerId: 14,
    serviceId: 11,
    ownerTypeCode: "GROUP",
    ownerName: "인증/권한 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 15,
    serviceId: 11,
    ownerTypeCode: "USER",
    ownerName: "한지민(금융ITO)",
    responsibilityCode: "SUB"
  },
  {
    serviceOwnerId: 26,
    serviceId: 20,
    ownerTypeCode: "GROUP",
    ownerName: "메시징/알림 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 33,
    serviceId: 26,
    ownerTypeCode: "GROUP",
    ownerName: "VOC 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 18,
    serviceId: 13,
    ownerTypeCode: "GROUP",
    ownerName: "인증/권한 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 32,
    serviceId: 25,
    ownerTypeCode: "GROUP",
    ownerName: "CS 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 12,
    serviceId: 9,
    ownerTypeCode: "GROUP",
    ownerName: "대내외계 솔루션 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 21,
    serviceId: 15,
    ownerTypeCode: "GROUP",
    ownerName: "채널통합 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 5,
    serviceId: 3,
    ownerTypeCode: "GROUP",
    ownerName: "CM/다이렉트 업무 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 38,
    serviceId: 31,
    ownerTypeCode: "GROUP",
    ownerName: "융자 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 3,
    serviceId: 1,
    ownerTypeCode: "GROUP",
    ownerName: "채널계 온콜그룹",
    responsibilityCode: "ALERT"
  },
  {
    serviceOwnerId: 1,
    serviceId: 1,
    ownerTypeCode: "GROUP",
    ownerName: "모바일 업무 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 2,
    serviceId: 1,
    ownerTypeCode: "USER",
    ownerName: "박서연(금융ITO)",
    responsibilityCode: "SUB"
  },
  {
    serviceOwnerId: 4,
    serviceId: 2,
    ownerTypeCode: "GROUP",
    ownerName: "홈페이지 업무 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 11,
    serviceId: 8,
    ownerTypeCode: "GROUP",
    ownerName: "마이데이터 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 8,
    serviceId: 6,
    ownerTypeCode: "GROUP",
    ownerName: "모바일 오피스 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 27,
    serviceId: 21,
    ownerTypeCode: "GROUP",
    ownerName: "문서/이미지 솔루션 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 34,
    serviceId: 27,
    ownerTypeCode: "GROUP",
    ownerName: "방카 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 36,
    serviceId: 29,
    ownerTypeCode: "GROUP",
    ownerName: "재무회계 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 37,
    serviceId: 30,
    ownerTypeCode: "GROUP",
    ownerName: "영업관리 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 7,
    serviceId: 5,
    ownerTypeCode: "GROUP",
    ownerName: "영업지원 업무 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 39,
    serviceId: 32,
    ownerTypeCode: "GROUP",
    ownerName: "인사/총무/감사 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 31,
    serviceId: 24,
    ownerTypeCode: "GROUP",
    ownerName: "TM 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 29,
    serviceId: 22,
    ownerTypeCode: "GROUP",
    ownerName: "데이터/분석계 온콜그룹",
    responsibilityCode: "ALERT"
  },
  {
    serviceOwnerId: 28,
    serviceId: 22,
    ownerTypeCode: "GROUP",
    ownerName: "정보계 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 20,
    serviceId: 14,
    ownerTypeCode: "GROUP",
    ownerName: "대내외계 온콜그룹",
    responsibilityCode: "ALERT"
  },
  {
    serviceOwnerId: 19,
    serviceId: 14,
    ownerTypeCode: "GROUP",
    ownerName: "채널통합 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 35,
    serviceId: 28,
    ownerTypeCode: "GROUP",
    ownerName: "퇴직연금/퇴직보험 담당그룹",
    responsibilityCode: "MAIN"
  },
  {
    serviceOwnerId: 13,
    serviceId: 10,
    ownerTypeCode: "GROUP",
    ownerName: "대내외계 솔루션 담당그룹",
    responsibilityCode: "MAIN"
  }
];

export const incidents: IncidentRecord[] = [
  {
    incidentId: 2,
    incidentTypeCode: "SERVER",
    serverId: 9,
    incidentStatusCode: "OPEN",
    severityCode: "MAJOR",
    title: "대외계 MCI 2호기 네트워크 간헐 단절",
    description: "if-prd-mci02 서버의 기관망 구간 TCP 세션 재전송이 증가하여 일부 대외 전문 처리 지연 발생",
    startedAt: "2026-05-20 10:28",
    manualRegisteredYn: "Y",
    registeredBy: "CV1007"
  },
  {
    incidentId: 1,
    incidentTypeCode: "SERVICE",
    serviceId: 11,
    incidentStatusCode: "OPEN",
    severityCode: "CRITICAL",
    title: "SSO/EAM 로그인 응답 지연",
    description: "SSO 세션 검증 API 응답 시간이 급증하여 모바일/홈페이지/영업지원 로그인 흐름이 지연되는 시나리오",
    startedAt: "2026-05-20 09:12",
    manualRegisteredYn: "Y",
    registeredBy: "CV1012"
  },
  {
    incidentId: 3,
    incidentTypeCode: "SERVICE",
    serviceId: 8,
    incidentStatusCode: "MONITORING",
    severityCode: "MAJOR",
    title: "마이데이터 제공 API 전송 지연",
    description: "외부 전송기관 호출 집중으로 제공 API 평균 응답 시간이 상승했으며 현재 스케일 조정 후 모니터링 중",
    startedAt: "2026-05-19 08:40",
    manualRegisteredYn: "Y",
    registeredBy: "CV1009"
  },
  {
    incidentId: 4,
    incidentTypeCode: "SERVICE",
    serviceId: 20,
    incidentStatusCode: "RESOLVED",
    severityCode: "MINOR",
    title: "알림톡 발송 큐 적체",
    description: "UMS 발송 큐 적체로 알림톡 일부가 5~10분 지연되었으며 큐 정리 및 재시도 처리 완료",
    startedAt: "2026-05-18 14:05",
    endedAt: "2026-05-18 15:10",
    manualRegisteredYn: "Y",
    registeredBy: "CV1013"
  },
  {
    incidentId: 5,
    incidentTypeCode: "SERVER",
    serverId: 7,
    incidentStatusCode: "RESOLVED",
    severityCode: "MAJOR",
    title: "기간계 배치 서버 디스크 사용률 임계치 초과",
    description: "배치 로그 파티션 사용률 95% 초과로 일부 야간 배치 재처리 후 정상화",
    startedAt: "2026-05-17 23:30",
    endedAt: "2026-05-18 01:15",
    manualRegisteredYn: "Y",
    registeredBy: "CV1010"
  },
  {
    incidentId: 6,
    incidentTypeCode: "SERVICE",
    serviceId: 22,
    incidentStatusCode: "RESOLVED",
    severityCode: "MAJOR",
    title: "정보계 마트 적재 지연",
    description: "전일 계약 데이터 적재 배치 지연으로 BI 리포트 일부 수치 갱신이 늦어진 시나리오",
    startedAt: "2026-05-16 06:20",
    endedAt: "2026-05-16 08:05",
    manualRegisteredYn: "Y",
    registeredBy: "CV1014"
  },
  {
    incidentId: 7,
    incidentTypeCode: "SERVICE",
    serviceId: 17,
    incidentStatusCode: "RESOLVED",
    severityCode: "NOTICE",
    title: "GitLab 정기 패치 작업",
    description: "보안 패치 반영을 위한 계획 작업. 서비스 영향은 사전 공지 범위 내에서 종료",
    startedAt: "2026-05-15 21:00",
    endedAt: "2026-05-15 22:20",
    manualRegisteredYn: "Y",
    registeredBy: "CV1011"
  }
];

export const incidentImpacts: IncidentImpactRecord[] = [
  {
    impactId: 11,
    incidentId: 2,
    impactedServiceId: 7,
    impactLevel: 1,
    impactPathText: "if-prd-mci02→MEGAWARE_HUB",
    directYn: "Y"
  },
  {
    impactId: 13,
    incidentId: 2,
    impactedServiceId: 9,
    impactLevel: 1,
    impactPathText: "if-prd-mci02→GOV_PUBLIC_IF",
    directYn: "Y"
  },
  {
    impactId: 12,
    incidentId: 2,
    impactedServiceId: 8,
    impactLevel: 1,
    impactPathText: "if-prd-mci02→MYDATA_PROVIDER",
    directYn: "Y"
  },
  {
    impactId: 10,
    incidentId: 2,
    impactedServiceId: 14,
    impactLevel: 1,
    impactPathText: "if-prd-mci02→MCI_GATEWAY",
    directYn: "Y"
  },
  {
    impactId: 15,
    incidentId: 2,
    impactedServiceId: 3,
    impactLevel: 2,
    impactPathText: "DIRECT_SALES_WEB→MEGAWARE_HUB",
    directYn: "N"
  },
  {
    impactId: 14,
    incidentId: 2,
    impactedServiceId: 29,
    impactLevel: 2,
    impactPathText: "COLLECTION_PAYMENT→MEGAWARE_HUB",
    directYn: "N"
  },
  {
    impactId: 1,
    incidentId: 1,
    impactedServiceId: 11,
    impactLevel: 1,
    impactPathText: "SSO_EAM",
    directYn: "Y"
  },
  {
    impactId: 9,
    incidentId: 1,
    impactedServiceId: 15,
    impactLevel: 2,
    impactPathText: "API_GATEWAY→SSO_EAM",
    directYn: "N"
  },
  {
    impactId: 4,
    incidentId: 1,
    impactedServiceId: 3,
    impactLevel: 2,
    impactPathText: "DIRECT_SALES_WEB→SSO_EAM",
    directYn: "N"
  },
  {
    impactId: 8,
    incidentId: 1,
    impactedServiceId: 31,
    impactLevel: 2,
    impactPathText: "LOAN_CORE→SSO_EAM",
    directYn: "N"
  },
  {
    impactId: 2,
    incidentId: 1,
    impactedServiceId: 1,
    impactLevel: 2,
    impactPathText: "MOBILE_APP→SSO_EAM",
    directYn: "N"
  },
  {
    impactId: 3,
    incidentId: 1,
    impactedServiceId: 2,
    impactLevel: 2,
    impactPathText: "HOMEPAGE_WEB→SSO_EAM",
    directYn: "N"
  },
  {
    impactId: 6,
    incidentId: 1,
    impactedServiceId: 6,
    impactLevel: 2,
    impactPathText: "MOBILE_E_CONTRACT→SSO_EAM",
    directYn: "N"
  },
  {
    impactId: 7,
    incidentId: 1,
    impactedServiceId: 27,
    impactLevel: 2,
    impactPathText: "BANK_PORTAL→SSO_EAM",
    directYn: "N"
  },
  {
    impactId: 5,
    incidentId: 1,
    impactedServiceId: 5,
    impactLevel: 2,
    impactPathText: "SALES_PORTAL→SSO_EAM",
    directYn: "N"
  },
  {
    impactId: 16,
    incidentId: 3,
    impactedServiceId: 8,
    impactLevel: 1,
    impactPathText: "MYDATA_PROVIDER",
    directYn: "Y"
  },
  {
    impactId: 17,
    incidentId: 3,
    impactedServiceId: 22,
    impactLevel: 2,
    impactPathText: "MYDATA_PROVIDER→DATA_MART",
    directYn: "N"
  },
  {
    impactId: 18,
    incidentId: 4,
    impactedServiceId: 20,
    impactLevel: 1,
    impactPathText: "UMS_ALIMTALK",
    directYn: "Y"
  },
  {
    impactId: 21,
    incidentId: 4,
    impactedServiceId: 19,
    impactLevel: 2,
    impactPathText: "ITSM_PORTAL→UMS_ALIMTALK",
    directYn: "N"
  },
  {
    impactId: 22,
    incidentId: 4,
    impactedServiceId: 18,
    impactLevel: 2,
    impactPathText: "JENNIFER_APM→UMS_ALIMTALK",
    directYn: "N"
  },
  {
    impactId: 20,
    incidentId: 4,
    impactedServiceId: 31,
    impactLevel: 2,
    impactPathText: "LOAN_CORE→UMS_ALIMTALK",
    directYn: "N"
  },
  {
    impactId: 19,
    incidentId: 4,
    impactedServiceId: 1,
    impactLevel: 2,
    impactPathText: "MOBILE_APP→UMS_ALIMTALK",
    directYn: "N"
  },
  {
    impactId: 25,
    incidentId: 5,
    impactedServiceId: 33,
    impactLevel: 1,
    impactPathText: "core-prd-batch01→IFRS17_ENGINE",
    directYn: "Y"
  },
  {
    impactId: 24,
    incidentId: 5,
    impactedServiceId: 30,
    impactLevel: 1,
    impactPathText: "core-prd-batch01→COMMISSION_CALC",
    directYn: "Y"
  },
  {
    impactId: 23,
    incidentId: 5,
    impactedServiceId: 10,
    impactLevel: 1,
    impactPathText: "core-prd-batch01→FILE_TRANSFER_HUB",
    directYn: "Y"
  },
  {
    impactId: 26,
    incidentId: 6,
    impactedServiceId: 22,
    impactLevel: 1,
    impactPathText: "DATA_MART",
    directYn: "Y"
  },
  {
    impactId: 27,
    incidentId: 6,
    impactedServiceId: 23,
    impactLevel: 2,
    impactPathText: "BI_REPORTING→DATA_MART",
    directYn: "N"
  },
  {
    impactId: 28,
    incidentId: 6,
    impactedServiceId: 33,
    impactLevel: 2,
    impactPathText: "IFRS17_ENGINE→DATA_MART",
    directYn: "N"
  },
  {
    impactId: 29,
    incidentId: 6,
    impactedServiceId: 28,
    impactLevel: 2,
    impactPathText: "RETIREMENT_CORE→DATA_MART",
    directYn: "N"
  },
  {
    impactId: 30,
    incidentId: 7,
    impactedServiceId: 17,
    impactLevel: 1,
    impactPathText: "GITLAB_PLATFORM",
    directYn: "Y"
  }
];
